Makefile: Sync script func and scripts
Unfortunately this is a large commit in order to be
atomic, such is the nature of gnu-make++bash.

The aim here is to resync our Makefile with upstreams
and the focus of this commit is specifically around
the various scripts and func that burn in version numbers
and check OS features.

Squash in,
  util/getrevision.sh: Take upstreams version

  util/z60_flashrom.rules: Import from upstream
  util/list_yet_unsupported_chips.sh: Import from upstream
  util/flashrom_partial_write_test.sh: Import from upstream
  util/git-hooks: Import from upstream

BUG=b:171014265
BRANCH=none
TEST=emerge and test on DUT that cli gives correct strings.

Disallow-Recycled-Builds: test-failures
Cq-Depend: chromium:2491623
Signed-off-by: Edward O'Callaghan <quasisec@google.com>
Change-Id: Ieb34bb7b03cec62ba7846b1ee180686a0cb5c41d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/flashrom/+/2477704
Tested-by: Edward O'Callaghan <quasisec@chromium.org>
Commit-Queue: Edward O'Callaghan <quasisec@chromium.org>
Reviewed-by: Sam McNally <sammc@chromium.org>
Auto-Submit: Edward O'Callaghan <quasisec@chromium.org>

diff --git a/util/git-hooks/pre-push b/util/git-hooks/pre-push
--- a/util/git-hooks/pre-push
+++ b/util/git-hooks/pre-push
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # A hook script to verify what is about to be pushed.  Called by "git
 # push" after it has checked the remote status, but before anything has been
@@ -22,15 +22,21 @@ url="$2"
 zero=0000000000000000000000000000000000000000
 
 upstream_pattern="github\.com.flashrom/flashrom(\.git)?|flashrom\.org.git/flashrom(\.git)?"
-precious_branches=( stable staging )
 
-# Only care about the upstream repository
+# Only care about the upstream repositories
 if echo "$url" | grep -q -v -E "$upstream_pattern" ; then
 	exit 0
 fi
 
 while read local_ref local_sha remote_ref remote_sha ; do
-	if [ "$remote_ref" != "refs/heads/staging" -a "$remote_ref" != "refs/heads/stable" ]; then
+
+	# Only allow the stable and staging branches as well as versioned stable branches (e.g., 0.0.x).
+	# The matching expression's RE is always anchored to the first character (^ is undefined).
+	# The outer parentheses are needed to print out the whole matched string.
+	version=$(expr ${remote_ref#*refs/heads/} : '\(\([0-9]\+\.\)\{2,\}x\)$')
+	if [ "$remote_ref" != "refs/heads/staging" ] && \
+	   [ "$remote_ref" != "refs/heads/stable" ] && \
+	   [ -z "$version" ]; then
 		echo "Feature branches not allowed ($remote_ref)." >&2
 		exit 1
 	fi
@@ -38,37 +44,32 @@ while read local_ref local_sha remote_ref remote_sha ; do
 	if [ "$local_sha" = $zero ]; then
 		echo "Deletion of branches is prohibited." >&2
 		exit 1
-	else
-		if [ "$remote_sha" = "$zero" ]; then
-			echo "No new branches allowed." >&2
-			exit 1
-		else
-			range="$remote_sha..$local_sha"
-		fi
-
-		# Check for Signed-off-by and Acked-by
-		commit=$(git rev-list -n 1 --all-match --invert-grep -E \
-			--grep '^Signed-off-by: .+ <.+@.+\..+>$' --grep '^Acked-by: .+ <.+@.+\..+>$' "$range")
-		if [ -n "$commit" ]; then
-			echo "No Signoff or Ack found in commit $local_sha in $local_ref, not pushing." >&2
-			exit 1
-		fi
-
-		# Make _really_ sure we do not rewrite precious history
-		for lbranch in "${precious_branches[@]}"; do
-			if [ "$remote_ref" = "refs/heads/$lbranch" ]; then
-				nonreachable=$(git rev-list $remote_sha ^$local_sha)
-				if [ -n "$nonreachable" ]; then
-					echo "Only fast-forward pushes are allowed on $lbranch." >&2
-					echo "$nonreachable is not included in $remote_sha while pusing to $remote_ref" >&2
-					exit 1
-				fi
-			fi
-		done
-
-		# FIXME: check commit log format (subject without full stop at the end etc).
-		# FIXME: do buildbot checks if authorized?
 	fi
+
+	# Check for Signed-off-by and Acked-by
+	commit=$(git rev-list -n 1 --all-match --invert-grep -E \
+		--grep '^Signed-off-by: .+ <.+@.+\..+>$' \
+		--grep '^Acked-by: .+ <.+@.+\..+>$' \
+		"$remote_sha..$local_sha")
+	if [ -n "$commit" ]; then
+		echo "Commit $local_sha in $local_ref is missing either \"Signed-off-by\"" \
+			" or \"Acked-by\" lines, not pushing." >&2
+		exit 1
+	fi
+
+	# Make _really_ sure we do not rewrite history of any head/branch
+	if [ "${remote_ref#*refs/heads/}" != "$remote_ref" ]; then
+		nonreachable=$(git rev-list $remote_sha ^$local_sha | head -1)
+		if [ -n "$nonreachable" ]; then
+			echo "Only fast-forward pushes are allowed on branches." >&2
+			echo "At least $nonreachable is not included in $remote_sha while pushing to " \
+			     "$remote_ref" >&2
+			exit 1
+		fi
+	fi
+
+	# FIXME: check commit log format (subject without full stop at the end etc).
+	# FIXME: do buildbot checks if authorized?
 done
 
 exit 0
